### ISSUE TITLE
weasel-pageant regularly dies

### ISSUE THREAD

**Issue by chris-morgan** [vuori/weasel-pageant#2] opened 2018-01-31 06:37 UTC
I find that `weasel-pageant` dies quite regularly, though I’m not sure what triggers its death. Sometimes it’ll be fine for ages, but sometimes it’ll fall over when I use it, e.g. spawn bash and it’s fine at that point, but then try to run `ssh` and the agent falls over some time during instantiation, so that it fails to use the agent; or in another case, it connects fine, but then dies somewhere along the way, no longer being available for forwarding. So then I start another terminal to get it going again.

I’m quite willing to do advanced diagnosis.

**Comment by vuori** [comment] 2018-01-31 07:53
What version of Windows and which Linux distribution are you using? Are you using the standard PuTTy Pageant or something else?

Can you try running `weasel-pageant` with the `-d` flag and see if it logs anything when it exits?

I've never seen this, but my guess is that the Win32 helper process is exiting for some reason.

**Comment by Tomeamis** [comment] 2018-03-07 12:33
I have encountered this as well.

I am using Windows 10 Home build 16299, with the default bash and Pageant bundled with PuTTy.
It seems that when the bash window that started `weasel-pageant` (the `conhost.exe`) closes, `helper.exe` dies as well, so other instances of bash then have no way to connect to Pageant.

Also, exiting the shell (by exit) in said window doesn't close it, instead it just prints "logout" and pretty much hangs until it is closed by other means (the window's close button, for example).

The socket and `weasel-pageant` continue existing until something attempts to use the agent, at which point `weasel-pageant` notices that it cannot connect to the agent and dies as well, taking the socket with it.

**Comment by chris-morgan** [comment] 2018-03-08 00:33
@Tomeamis Yeah, there’s that one too, but that was different to the situation which I was describing. To resolve *that* issue, the process may need to be disowned or similar.

@vuori After I reported this bug, I haven’t observed the problem occurring again. A few days later, I switched computer; I’m now switching computers again due to a defective device, but I’ll chime in again if it starts happening again.

**Comment by vuori** [comment] 2018-03-08 09:20
I have seen the terminal-hangs problem, which is probably related to the fact that the `init` process executing the helper is hanging on to the TTY. This is a side-effect of a workaround for what appeared to be a file-descriptor handling bug in WSL in CU (in brief, some combinaton of forking and file descriptor manipulation leads to an inability to establish functional pipes to a win32 process).

The best fix would be to have the helper restart as necessary. I'll see if I have time to investigate this week whether things are better in FCU and/or if the problem can be worked around while allowing helper restarts.

**Comment by vuori** [comment] 2018-03-11 18:56
Ok, I think I have a workaround for what looks like a pretty weird bug in WSL. This allows `weasel-pageant` to restart the helper process (which should fix the unexpected exits) and properly detach from the tty in daemon mode (which should fix the hanging terminals).

This is going to need some cleanup that I don't have time to do now, but I'll try to put out a test release in a few days.

**Comment by vuori** [comment] 2018-03-13 23:32
After more investigation, it appears that there are difficult-to-fix problems due to several WSL issues. As mentioned in the previous comments, currently the helper dies when its parent conhost exits. With the attempted fix, the helper stays alive but will instead becomes completely unresponsive. Also, the conhost still hangs on exit.

I think the best workaround at the moment is to use per-WSL-window `weasel-agent` processes instead of the socket reuse mode. Either just  leave out the `-a` and `-r` flags or start your shell as a `weasel-agent` subprocess.

A version capable of restarting the helper is in the `feature/helper-restart` branch if someone wants to compile and play with it, but I suspect it will not be particularly useful for most users as it stands. I have a couple of ideas on how to deal with the hanging problem, but it may be a while before I have time to look into this.

Since Insider Build 17063 introdcued support for native Windows-side Unix domain sockets, a better approach would seem to be to rewrite `weasel-pageant` as a standalone Win32 app using native sockets when the support presumably comes out in the next Windows 10 release. When Cygwin/MinGW-w64 adds support for them, the replacement should in principle be able to supercede both `weasel-pageant` and `ssh-pageant`.

**Comment by Ciantic** [comment] 2018-03-14 23:20
I've tried to read this thread, I haven't yet used the weasel-pageant, but what is the advice how to use this so that it's most stable?

**Comment by orestes** [comment] 2018-03-17 00:45
@vuori you could update the README to warn about the `-a` and `-r` flags since right now you're prescribing them in the launch command

**Comment by vuori** [comment] 2018-03-31 16:46
Version 1.1 is available on the releases page. I recommend removing the `-a` flag from your shell init. The new version fixes the terminal hanging problem for me both with native console and wsltty. The helper process should also restart as needed, but if problems appear they should be localized to a single WSL window.

**Closed** 2018-04-03 11:08 UTC
Labels: bug

**Comment by chris-morgan** [comment] 2018-04-30 02:15
I’m still definitely hitting this problem with 1.1, where weasel-pageant dies. Sure, it only affects one window now without -a, but it’s still an issue. ☹

**Comment by vuori** [comment] 2018-05-01 08:46
Please collect logs and if possible steps to reproduce as described in the bug reporting section of the README and open a new issue.

**Comment by lusitania** [comment] 2018-12-03 12:47
The issue didn't go away for me, too. Even stranger the binary appears to still be on v1.0:
```
$ weasel-pageant-1.1/weasel-pageant --version
weasel-pageant 1.0
Copyright 2017  Valtteri Vuorikoski
Based on ssh-pageant, copyright 2009-2014  Josh Stone
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by vuori** [comment] 2018-12-12 15:09
The current release binary shows the wrong version number in `--version` output. If you have figured a way to reproduce the exit reliably or have other new information that might reveal the cause, please post it in the new issue for this problem: https://github.com/vuori/weasel-pageant/issues/7
